# =========================================================
# AP AI V4 Stable
# Created by : Amarchand Meghwal
# =========================================================

"""
Global Theme Configuration

Do not edit this file after creation.
Every screen in AP AI uses these constants.
"""

# -------------------------
# APP INFO
# -------------------------

APP_NAME = "AP AI"
APP_VERSION = "V4 Stable"
DEVELOPER = "Amarchand Meghwal"

# -------------------------
# COLORS
# -------------------------

PRIMARY = "#00B8FF"
PRIMARY_DARK = "#0077B6"

ACCENT = "#00E5FF"

BACKGROUND = "#0B1220"

SURFACE = "#121A2A"

CARD = "#1A2436"

TEXT = "#FFFFFF"

TEXT_SECONDARY = "#9FB3C8"

SUCCESS = "#00C853"

WARNING = "#FFC107"

ERROR = "#FF5252"

DIVIDER = "#2B3445"

# -------------------------
# RADIUS
# -------------------------

CARD_RADIUS = 22

BUTTON_RADIUS = 18

TEXTFIELD_RADIUS = 16

# -------------------------
# SPACING
# -------------------------

PADDING = 16

MARGIN = 16

GAP = 12

# -------------------------
# ICONS
# -------------------------

ICON_HOME = "home"

ICON_CHAT = "message-text"

ICON_VOICE = "microphone"

ICON_MEMORY = "brain"

ICON_TOOLS = "tools"

ICON_SETTINGS = "cog"

ICON_AI = "robot"

# -------------------------
# ANIMATION
# -------------------------

SCREEN_TRANSITION = 0.25

BUTTON_ANIMATION = 0.15

CARD_ANIMATION = 0.20
